# NumPy

## Markdown Cheatsheet

https://ingeh.medium.com/markdown-for-jupyter-notebooks-cheatsheet-386c05aeebed#:~:text=Bullets%3A%20Use%20the%20dash%20sign,Numbered%20lists%3A%20Start%20with%201.

In [1]:
import numpy as np

In [2]:
#here the np.int shows that the data is 8 bits, we can use 32, 64 bits according to the size of our numbers
myarr= np.array([3,76,98,443,2,4,1], np.int8)

In [3]:
myarr

array([  3,  76,  98, -69,   2,   4,   1], dtype=int8)

In [4]:
myarr[3]

-69

**Functions on myarr**

*np.array*
*a.shape*
*a.size*
*a.dtype*


In [5]:
# .shape(rows,colums), here as myarr is one dimentional it shows it has 7 elements
myarr.shape

(7,)

In [6]:
myarr= np.array([[3,76,98,443,2,4,1]], np.int8)
myarr.shape
#here it clearly shows 1 row and 7 colums and the array is 2 dimentional(double [])

(1, 7)

In [7]:
myarr.dtype
#we can change it to int32,int64 or anything else like float32 depending on the value of our data

dtype('int8')

There are 6 general mechanisms for creating arrays:

1. Conversion from other Python structures (i.e. lists and tuples)

2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

3. Replicating, joining, or mutating existing arrays

4. Reading arrays from disk, either from standard or custom formats

5. Creating arrays from raw bytes through the use of strings or buffers

6. Use of special library functions (e.g., random)



In [8]:
#1. Conversion from other Python structures (i.e. lists and tuples)
listarr= np.array([[2,5,6,8] , [7,8,3,4] , [2,8,4,0]])
listarr


array([[2, 5, 6, 8],
       [7, 8, 3, 4],
       [2, 8, 4, 0]])

In [9]:
listarr.dtype

dtype('int32')

In [10]:
listarr.size

12

In [11]:
#2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
zeroes= np.zeros((3,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
r= np.arange(13)
r
# arange function gives an array in the range of the given number also n-1 position.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
ls= np.linspace(1,4,4)
ls

#linspace shows linearly spaced elements linspace(starting number, ending number, range)

array([1., 2., 3., 4.])

In [14]:
lnn= np.linspace(1,3,4)
lnn


array([1.        , 1.66666667, 2.33333333, 3.        ])

In [15]:
emp= np.empty([3,6]) #what it does is gives us an array of 4,6 and all the items will be random inside of it
emp

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306,
        1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306,
        1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307,
        9.34609790e-307, 3.91792279e-317, 0.00000000e+000]])

In [16]:
empsp= np.array(lnn)
empsp

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [17]:
# Creates identity matrix
ide= np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
ide.shape

(4, 4)

In [19]:
ide.size


16

In [20]:
#reshape changes the rows and colums or divides big matrices into smaller ones provided that they're equally distributed
mat= np.arange(99)
mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
mat.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [22]:
mat.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [23]:
mat.ravel() #it will change the reshaped array back to a 1D array block

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
mat.shape


(99,)

*Attributes of arrays using NumPy*

In [25]:
x= [[2,1,4] , [7,9,3] , [2,1,1]]
ar= np.array(x)
ar

array([[2, 1, 4],
       [7, 9, 3],
       [2, 1, 1]])

In [26]:
ar.sum(axis=0) #gives the sum of all columns

array([11, 11,  8])

In [27]:
ar.sum(axis=1) #gives the sum of all rows into a 1D matrix

array([ 7, 19,  4])

In [28]:
ar.T #transpose matrix

array([[2, 7, 2],
       [1, 9, 1],
       [4, 3, 1]])

In [29]:
ar.flat #this returns an iterator therefore we can use in in a range and print things accordingly

In [30]:
for i in ar.flat:
    print (i)

2
1
4
7
9
3
2
1
1


In [31]:
ar.ndim   #tells the directions like in this case 2, rows and column

2

In [32]:
ar.nbytes  #tells about the number of bytes used by the array

36

In [33]:
n= np.array([2,45,67,34,11,2,8])
n.argmax()        #a function which gives the index of the maximum valuen.

2

In [34]:
n.argmin()

0

In [35]:
ar.argmax()

4

In [36]:
n.argsort()   #gives a array of sorted "INDICIES"

array([0, 5, 6, 4, 3, 1, 2], dtype=int64)

In [37]:
ar.argmin()

1

In [38]:
ar.argsort()

array([[1, 0, 2],
       [2, 0, 1],
       [1, 2, 0]], dtype=int64)

In [39]:
ar.argmax(axis=0)

array([1, 1, 0], dtype=int64)

In [40]:
ar.argmax(axis=1)

array([2, 1, 0], dtype=int64)

In [41]:
ar.argsort(axis=0)

array([[0, 0, 2],
       [2, 2, 1],
       [1, 1, 0]], dtype=int64)

In [42]:
ar.argsort(axis=1)

array([[1, 0, 2],
       [2, 0, 1],
       [1, 2, 0]], dtype=int64)

In [44]:
ar.ravel()

array([2, 1, 4, 7, 9, 3, 2, 1, 1])

In [50]:
ar.reshape(9,1)

array([[2],
       [1],
       [4],
       [7],
       [9],
       [3],
       [2],
       [1],
       [1]])

In [51]:
ar


array([[2, 1, 4],
       [7, 9, 3],
       [2, 1, 1]])

In [52]:
ar2= np.array([[3, 0, 9],
       [4, 3, 3],
       [2, 0, 6]])
ar+ar2                 ''' we can add,multiply,subtract,divide etc arrays not just concatenate them or
                         throw error like lists. Pretty cool !!!!!'''

array([[ 5,  1, 13],
       [11, 12,  6],
       [ 4,  1,  7]])

In [56]:
ar*ar2

array([[ 6,  0, 36],
       [28, 27,  9],
       [ 4,  0,  6]])

In [60]:
np.sqrt(ar)

array([[1.41421356, 1.        , 2.        ],
       [2.64575131, 3.        , 1.73205081],
       [1.41421356, 1.        , 1.        ]])

In [61]:
ar.sum()

30

In [62]:
ar.max() #here it gives the max value not index like argmax. Same goes for the minimum

9

In [66]:
np.where(ar>5) #returns a tupple with positions like here greater than 5 is present at 1st row and 1st column

(array([1], dtype=int64), array([1], dtype=int64))

In [67]:
type(np.where(ar>5))

tuple

In [68]:
np.count_nonzero(ar) #returns no' of elements which are not zero


9

In [69]:
np.nonzero(ar) #gives indicies of non zero elements, returns a tuple for each axis

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [73]:
ar.itemsize  #returns the byte size of each element on the NumPy array

4

In [74]:
ar.itemsize * ar.size #hence gives the total size of the array

36

In [77]:
import sys
lst= ([2, 1, 4, 7, 9, 3, 2, 1, 1])
sys.getsizeof(1) * len(lst)

'''This shows how arrays are so much effecient in saving memory'''

252

**Attributes and Functions**

https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html

**Boolean Indexing**

In [82]:
n= [1,5,6,4,99,8,2,5,3,0,3]
n[: 3] #prints until the n-1 position


[1, 5, 6]

In [83]:
boo= np.array(n)
boo[: 6]

array([ 1,  5,  6,  4, 99,  8])

In [84]:
ar

array([[2, 1, 4],
       [7, 9, 3],
       [2, 1, 1]])

In [85]:
ar[1,2]

3

In [86]:
ar[:, 2]

array([4, 3, 1])

In [88]:
ar[0:3, 2]

array([4, 3, 1])

In [92]:
np.vstack((ar, ar2))

array([[2, 1, 4],
       [7, 9, 3],
       [2, 1, 1],
       [3, 0, 9],
       [4, 3, 3],
       [2, 0, 6]])

In [93]:
np.hstack((ar,ar2))

array([[2, 1, 4, 3, 0, 9],
       [7, 9, 3, 4, 3, 3],
       [2, 1, 1, 2, 0, 6]])

In [97]:
np.hsplit(ar,3)

[array([[2],
        [7],
        [2]]),
 array([[1],
        [9],
        [1]]),
 array([[4],
        [3],
        [1]])]

In [99]:
np.hsplit(ar,3)

[array([[2],
        [7],
        [2]]),
 array([[1],
        [9],
        [1]]),
 array([[4],
        [3],
        [1]])]

In [101]:
b= ar>4
print(b) #this returns a boolean array a/c to the condition given

[[False False False]
 [ True  True False]
 [False False False]]


In [102]:
ar[b]

array([7, 9])